- .gitmodules
- cczoo/rats-tls/README.md
Signed-off-by: Zhiwei Han <zhiwei1.han@intel.com>
> Add rats-tls module

- documents/readthedoc/docs/source/Solutions/ehsm-kms/index.md
And provide a workaround on readthedocs error links
Signed-off-by: Yang Huang <yang.huang@intel.com>
> Bump ehsm KMS to 5c91d6d

- documents/readthedoc/docs/source/index.rst
Signed-off-by: RodgerZhu <yunge.zhu@intel.com>
> Add rats-tls doc index in readthedoc

- documents/readthedoc/docs/source/Solutions/rats-tls/index.md
- documents/readthedoc/docs/source/index.rst
> Refine rats-tls index in doc

- documents/readthedoc/docs/source/Solutions/rats-tls/index.md
Signed-off-by: RodgerZhu <yunge.zhu@intel.com>
> Refine rats-tls index in the doc

- README.md
- cczoo/ehsm/README.md
- documents/readthedoc/docs/source/Cloud/cloudDeployment.md
Signed-off-by: RodgerZhu <yunge.zhu@intel.com>
> Change eHSM to eHSM-KMS

- README.md
Signed-off-by: Liang Yang <liang3.yang@intel.com>
> README: add tdx support in rats-tls description

- cczoo/horizontal_fl/hfl-tensorflow/python.manifest.template
Fix the remote attsetation issue and create a dir to save model.
> Add the model dir and update the remote attestation config

- cczoo/cross_lang_framework/clf_client/app/Makefile
- cczoo/cross_lang_framework/clf_client/app/clf_test.java
- cczoo/cross_lang_framework/clf_client/app/java.manifest.template
- cczoo/cross_lang_framework/clf_client/clf_client.c
- cczoo/cross_lang_framework/clf_client/clf_client.h
- cczoo/cross_lang_framework/clf_client/debug.c
- cczoo/cross_lang_framework/clf_client/java/Makefile
- cczoo/cross_lang_framework/clf_server/Makefile
- cczoo/cross_lang_framework/clf_server/clf_server.c
- cczoo/cross_lang_framework/clf_server/clf_server.conf
- cczoo/cross_lang_framework/clf_server/interact.c
- cczoo/cross_lang_framework/inc/cross_comm.h
> Cross lang framework

- documents/readthedoc/docs/source/Solutions/cross_language_framework_based_gramine/Readme.md
update readme, remove the meaningless word "image"
> remove the meaningless word "image"

- cczoo/cross_lang_framework/clf_client/app/rebuild.sh
- cczoo/cross_lang_framework/clf_client/java/rebuild.sh
- cczoo/cross_lang_framework/clf_server/rebuild.sh
- cczoo/cross_lang_framework/comm/util.c
> add file util.c and rebuild.sh

- cczoo/cross_lang_framework/clf_client/clf_local.c
- cczoo/cross_lang_framework/clf_client/clf_remote.c
Signed-off-by: Liang Fang <liang.a.fang@intel.com>
> add clf_local.c and clf_remote.c

- cczoo/cross_lang_framework/comm/fop.c
Signed-off-by: Liang Fang <liang.a.fang@intel.com>
> Fix bug: clf_server truncate file by mistake

- documents/readthedoc/docs/source/LibOS/libos.md
Fix link to Occulum GitHub and a small issue with wording.
NA
> [Docs] Fix link to Occulum github and small issue with wording

- cczoo/cross_lang_framework/clf_server/Makefile
> change Gramine path to lowercase

- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/client/download_model.sh
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/client/requirements.txt
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/client/resnet_client_grpc.py
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/build_gramine_tf_serving_image.sh
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/gramine_tf_serving.dockerfile
> Fix version of dependent package in tf-serving

- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/secret_prov/build_secret_prov_image.sh
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/secret_prov/secret_prov.dockerfile
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/build_gramine_tf_serving_image.sh
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/gramine_tf_serving.dockerfile
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/run_gramine_tf_serving.sh
- cczoo/tensorflow-serving-cluster/tensorflow-serving/kubernetes/deploy.yaml
- cczoo/tensorflow-serving-cluster/tensorflow-serving/setup_azure_vm.sh
- documents/readthedoc/docs/source/Cloud/cloudDeployment.md
- documents/readthedoc/docs/source/Solutions/tensorflow-serving-cluster/index.rst
> Add Azure deployment 

- cczoo/cross_lang_framework/clf_client/clf_client.c
- cczoo/cross_lang_framework/clf_client/clf_remote.c
- cczoo/cross_lang_framework/clf_client/debug.c
- cczoo/cross_lang_framework/clf_server/clf_server.c
- cczoo/cross_lang_framework/clf_server/clf_server.conf
- cczoo/cross_lang_framework/clf_server/interact.c
- cczoo/cross_lang_framework/comm/fop.c
- cczoo/cross_lang_framework/inc/cross_comm.h
Signed-off-by: Liang Fang <liang.a.fang@intel.com>
> make port and cert configurable

- cczoo/common/docker/occlum/README.md
- cczoo/grpc-ra-tls/README.md
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/client/client.dockerfile
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/secret_prov/secret_prov.dockerfile
- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/gramine_tf_serving.dockerfile
- documents/readthedoc/docs/source/Solutions/grpc-ra-tls/index.md
- documents/readthedoc/docs/source/Solutions/tensorflow-serving-cluster/index.rst
> Upgrade TF-Serving base image && Update readme

- cczoo/cross_lang_framework/auto_install_clf.bash
- cczoo/cross_lang_framework/install cr_lan framework .bash
> Add bash file to install cro_lan framework easily

- cczoo/horizontal_fl/README.md
- cczoo/horizontal_fl/recommendation_system/test-sgx.sh
- cczoo/horizontal_fl/setup_azure_vm.sh
- documents/readthedoc/docs/source/Solutions/horizontal-federated-learning/hfl.md
Update support for hfl deployments on Azure
Test hfl deployments (recommendation system and image classification) on Azure
> Update support for hfl deployments on Azure

- cczoo/common/docker/gramine/configs/etc/sgx_default_qcnl.conf
- cczoo/common/docker/occlum/configs/etc/sgx_default_qcnl.conf
- cczoo/common/docker/occlum/occlum-sgx-dev.dockerfile
- cczoo/grpc-ra-tls/README.md
- cczoo/grpc-ra-tls/gramine/CI-Examples/grpc/python/ratls/python.manifest.template
- cczoo/grpc-ra-tls/gramine/README.md
- cczoo/grpc-ra-tls/grpc/common/build_python.sh
- cczoo/grpc-ra-tls/occlum/README.md
- cczoo/grpc-ra-tls/occlum/demos/ra_tls/build_occlum_instance.sh
- cczoo/grpc-ra-tls/occlum/grpc-ratls-sgx-dev.dockerfile
- cczoo/grpc-ra-tls/start_container.sh
- cczoo/tensorflow-serving-cluster/kubernetes/ingress-nginx/deploy-nodeport.yaml
- cczoo/tensorflow-serving-cluster/kubernetes/install_kubernetes.sh
- documents/readthedoc/docs/source/Solutions/grpc-ra-tls/index.md
Fix kubernetes version in tensorflow-serving-cluster.
Update TEE docker images, and use ubuntu20.04 as base image.
Update grpc-ra-tls dev docker image name.
> Fix kubernetes version in tensorflow-serving-cluster && Update grpc-ra-tls docker image name

- cczoo/psi/gramine/CI-Examples/psi/cpp/Makefile
- cczoo/psi/gramine/build_docker_image.sh
- cczoo/psi/gramine/psi-gramine-sgx-dev.dockerfile
- cczoo/psi/start_container.sh
- documents/readthedoc/docs/source/index.rst
> Fix some known issues

- cczoo/common/docker/gramine/configs/root/start_aesm_service.sh
- cczoo/grpc-ra-tls/README.md
- cczoo/grpc-ra-tls/gramine/CI-Examples/grpc/python/ratls/python.manifest.template
- cczoo/grpc-ra-tls/grpc/common/build_cpp.sh
- cczoo/grpc-ra-tls/grpc/common/build_python.sh
- cczoo/grpc-ra-tls/occlum/demos/ra_tls/build_occlum_instance.sh
- documents/readthedoc/docs/source/Solutions/grpc-ra-tls/index.md
Signed-off-by: Bu Jianlin <jianlinx.bu@intel.com>
> Fix grpc-ra-tls merge error

- cczoo/horizontal_fl/README.md
- cczoo/horizontal_fl/anolisos_horizontal_fl.dockerfile
- cczoo/horizontal_fl/build_docker_image.sh
- cczoo/horizontal_fl/horizontal_fl.dockerfile
- cczoo/horizontal_fl/image_classification/anolisos.diff
- cczoo/horizontal_fl/patches/gramine/CI-Examples/ra-tls-mbedtls/build_install.sh
- cczoo/horizontal_fl/patches/tf/build.sh
- cczoo/horizontal_fl/recommendation_system/anolisos.diff
- cczoo/horizontal_fl/start_container.sh
- documents/readthedoc/docs/source/Solutions/horizontal-federated-learning/hfl.md
Enable gramine in anolisos and update docs and readme
> Enable gramine in anolisos and update docs and readme

- cczoo/common/docker/gramine/README.md
- cczoo/common/docker/gramine/build_docker_image.sh
- cczoo/common/docker/gramine/configs/root/start_aesm_service.sh
- cczoo/common/docker/gramine/gramine-sgx-dev.dockerfile
- cczoo/common/docker/occlum/README.md
- cczoo/common/docker/occlum/build_docker_image.sh
- cczoo/common/docker/occlum/configs/etc/sgx_default_qcnl.conf
- cczoo/common/docker/occlum/occlum-sgx-dev.dockerfile
- cczoo/psi/README.md
- cczoo/psi/gramine/CI-Examples/psi/cpp/Makefile
- cczoo/psi/gramine/CI-Examples/psi/cpp/grpc.manifest.template
- cczoo/psi/gramine/CI-Examples/psi/python/Makefile
- cczoo/psi/gramine/CI-Examples/psi/python/python.manifest.template
- cczoo/psi/gramine/build_docker_image.sh
- cczoo/psi/gramine/psi-gramine-sgx-dev.dockerfile
- cczoo/psi/grpc/common/build_python.sh
- cczoo/psi/start_container.sh
- documents/readthedoc/docs/source/Solutions/psi/images/psi.svg
- documents/readthedoc/docs/source/index.rst
Add support for Ubuntu 20.04 and gramine v1.2
> Branch dev/psi: Add support for Ubuntu 20.04 and gramine v1.2

- cczoo/vertical_fl/README.md
- cczoo/vertical_fl/apply_overlay.sh
- cczoo/vertical_fl/overlay/build_dev_docker_image.sh
- cczoo/vertical_fl/overlay/fedlearner-sgx-dev.dockerfile
- cczoo/vertical_fl/overlay/test-ps-sgx.sh
- documents/readthedoc/docs/source/Cloud/cloudDeployment.md
- documents/readthedoc/docs/source/Solutions/vertical-federated-learning/vfl.md
- Add vertical federated learning solution support for Azure deployments
- Update vertical_fl submodule to the latest commit from fedlearner fix_dev_sgx branch
- Fix port numbers in test-ps-sgx.sh
- Update VFL documentation
1. Test vertical federated learning solution deployment on Azure
2. Regression test vertical federated learning solution deployments on other cloud providers
> Add vertical federated learning solution support for Azure deployments

- cczoo/cross_lang_framework/ccp/clf_server.toml
- cczoo/cross_lang_framework/ccp/convert_clf_server_to_ccp_image.sh
- cczoo/cross_lang_framework/clf_server/clf_server.c
- cczoo/cross_lang_framework/docker/build_clf_client_app_docker_image.sh
- cczoo/cross_lang_framework/docker/clf_client.dockerfile
- cczoo/cross_lang_framework/docker/clf_client_app.dockerfile
- cczoo/cross_lang_framework/docker/clf_server.dockerfile
> add separated client app docker file and fix a bug

- cczoo/common/docker/gramine/anolisos-gramine-sgx-dev.dockerfile
- cczoo/common/docker/gramine/build_docker_image.sh
- cczoo/common/docker/gramine/gramine-sgx-dev:v1.2-anolisos.dockerfile
- cczoo/psi/README.md
- cczoo/psi/gramine/CI-Examples/psi/cpp/anolisos.diff
- cczoo/psi/gramine/CI-Examples/psi/python/anolisos.diff
- cczoo/psi/gramine/anolisos-psi-gramine-sgx-dev.dockerfile
- cczoo/psi/gramine/build_docker_image.sh
- cczoo/psi/start_container.sh
- documents/readthedoc/docs/source/Solutions/psi/PSI.md
> Enable psi in anolisos

- README.md
- cczoo/lr_infer_he_sgx/Dockerfile
- cczoo/lr_infer_he_sgx/README.md
- cczoo/lr_infer_he_sgx/build_docker_image.sh
- cczoo/lr_infer_he_sgx/start_container.sh
- documents/readthedoc/docs/source/Cloud/cloudDeployment.md
- documents/readthedoc/docs/source/Solutions/logistic-regression-inference-HE-SGX/index.md
Add Secure Logistic Regression Inference with HE and Intel SGX solution support for Azure deployments
> Add Secure Logistic Regression Inference solution support for Azure deployments

- cczoo/horizontal_fl/anolisos_horizontal_fl.dockerfile
- cczoo/horizontal_fl/horizontal_fl.dockerfile
- cczoo/horizontal_fl/image_classification/Makefile
- cczoo/horizontal_fl/image_classification/python.manifest.template
- cczoo/horizontal_fl/image_classification/test-sgx.sh
- cczoo/horizontal_fl/patches/gramine/CI-Examples/ra-tls-mbedtls/src/client.c
- cczoo/horizontal_fl/patches/tf/tensorflow/core/distributed_runtime/rpc/grpc_sgx_ra_tls_server.cc
- cczoo/horizontal_fl/patches/tf/tensorflow/core/distributed_runtime/rpc/grpc_sgx_ra_tls_utils.h
- cczoo/horizontal_fl/recommendation_system/Makefile
- cczoo/horizontal_fl/recommendation_system/python.manifest.template
- cczoo/horizontal_fl/recommendation_system/test-sgx.sh
- cczoo/horizontal_fl/start_container.sh
Upgrade gramine from v1.2 to v1.3.1
> Upgrade gramine from v1.2 to v1.3.1

- cczoo/psi/README.md
- cczoo/psi/configs/etc/sgx_default_qcnl.conf
- cczoo/psi/configs/root/start_aesm_service.sh
- cczoo/psi/gramine/CI-Examples/psi/cpp/Makefile
- cczoo/psi/gramine/CI-Examples/psi/cpp/build.sh
- cczoo/psi/gramine/build_docker_image.sh
- cczoo/psi/gramine/psi-gramine-sgx-dev.dockerfile
- cczoo/psi/grpc/v1.38.1/examples/cpp/psi/build.sh
- cczoo/psi/grpc/v1.38.1/examples/python/psi/server.py
- cczoo/psi/start_container.sh
1. Merge Gramine Dockerfile to PSI Dockerfile.
2. Support for Gramine v1.2.
3. Update docs.
> Support for Gramine v1.2 and update docs

- cczoo/cross_lang_framework/docker/clf_client.dockerfile
- cczoo/cross_lang_framework/docker/clf_server.dockerfile
remove cryptography to pass OSPDT
Signed-off-by: Liang Fang <liang.a.fang@intel.com>
> remove cryptography from dockerfile

- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/tf_serving/anolisos_gramine_tf_serving.dockerfile
Modify tensorflow_model_server install method
> Modify tensorflow_model_server install method

- cczoo/horizontal_fl/anolisos_horizontal_fl.dockerfile
- cczoo/horizontal_fl/horizontal_fl.dockerfile
> Added some miss components

- cczoo/horizontal_fl/horizontal_fl.dockerfile
> Fix app version

- cczoo/horizontal_fl/horizontal_fl.dockerfile
Reverts intel/confidential-computing-zoo#191
> Revert "Fix app version"

- cczoo/cross_lang_framework/ccp/Tooltip_for_clf_client.md
- cczoo/cross_lang_framework/ccp/Tooltip_for_clf_server.md
> add tootip for clf_server and clf_client

- cczoo/vertical_fl/README.md
- documents/readthedoc/docs/source/Solutions/tensorflow-serving-cluster/index.rst
- documents/readthedoc/docs/source/Solutions/vertical-federated-learning/vfl.md
Update VFL and tf-serving documentation based on user feedback.
Update VFL documentation to replace fedlearner git submodule with git clone.
Regression tested VFL on Azure.
> Update VFL and tf-serving documentation

- cczoo/horizontal_fl/horizontal_fl.dockerfile
The request submitted last time was based on the wrong version, which has been corrected this time.
> Fixed app version

- cczoo/tensorflow-serving-cluster/tensorflow-serving/docker/client/requirements.txt
> Upgrade tensorflow version

- cczoo/horizontal_fl/start_container.sh
This pr fix a syntax error in bash script `cczoo/horizontal_fl/start_container.sh`
```sh
cd cczoo/horizontal_fl
./start_container.sh ps0 127.0.0.1 ubuntu
```
> Fix horizontal_fl/start_container.sh script

- cczoo/common/docker/gramine/gramine-sgx-dev:v1.2-anolisos.dockerfile
- cczoo/psi/gramine/CI-Examples/psi/cpp/anolisos.diff
- cczoo/psi/gramine/CI-Examples/psi/python/anolisos.diff
- cczoo/psi/gramine/anolisos-psi-gramine-sgx-dev.dockerfile
Update psi Anolisos patch files and fix known issues in psi Anolisos Dockerfile.
> Branch dev/psi

- cczoo/cross_lang_framework/docker/start_clf_client_container.sh
- cczoo/cross_lang_framework/docker/start_clf_server_container.sh
> Updated the script to start the container

- cczoo/tdx-encrypted-vfs/get_secret/start_container.sh
> Use host network for tdx-encrypted-vfs docker

- documents/readthedoc/docs/source/Solutions/tensorflow-serving-cluster/cczoo_ppml_inference_azure.md
Update TF Serving (SGX) documentation
> Update TF Serving (SGX) documentation

- documents/readthedoc/docs/source/Solutions/grpc-ra-tls/index.md
Fixes typos and grammar. Standardizes paragraph padding, punctuation usage, code formatting, and multi-line code language for syntax highlighting. Formats references to other files as links.
> docs: Fix typos and styling

- cczoo/horizontal_fl_tdx/build_docker_image.sh
- cczoo/horizontal_fl_tdx/gcp/grpc_ratls.gcp.patch
- cczoo/horizontal_fl_tdx/gcp/tf_v2.6.diff
- cczoo/horizontal_fl_tdx/horizontal_fl_tdx.gcp.dockerfile
- cczoo/horizontal_fl_tdx/start_container.gcp.sh
- documents/readthedoc/docs/source/Solutions/tdx-hfl/tdx-hfl.md
Add HFL support for Google Cloud TDX
> Add HFL support for Google Cloud TDX

- cczoo/rag/backend/backend.dockerfile
- cczoo/rag/backend/pipelines/run_pipeline.py
- cczoo/rag/run.sh
> Fix known issues

- cczoo/rag/frontend/chatbot-rag/app.py
- cczoo/rag/run.sh
Bug fix:
1. Update prompt to answer gerneral questions.
2. Fix known issue when using remote attestion.
> Branch dev/rag: Fix known bugs

- .github/workflows/build-gprc-tls-docker-image.yml
- .github/workflows/build-hfl-docker-image.yml
- .github/workflows/build-main-docker-image.yml
- .github/workflows/build-tf-serving-docker-image.yml
This PR addresses token permission issues identified by OpenSSF Scorecard.
docker run -e GITHUB_AUTH_TOKEN=ghp_yourtokennotmine  gcr.io/openssf/scorecard:stable --checks Token-Permissions --repo=https://github.com/intel/confidential-computing-zoo
> Fixes Token-Permissions Issues Identified By Scorecard

- cczoo/confidential_ai/quote_generation/quote_generator.pyx
- cczoo/confidential_ai/quote_generation/setup.py
- cczoo/confidential_ai/quote_generation/td_report_parse.h
> Add quote generation componment

- cczoo/confidential_ai/open-webui-patch/v0.5.20-feature-cc-tdx-v1.0.patch
- cczoo/confidential_ai/tdx_measurement_plugin/quote_generator.pyx
update patches && get quote function
> Update patch & quote funation
